### ISSUE TITLE
error starting browser: exec: "google-chrome": executable file not found in $PATH

### ISSUE THREAD

**Issue by Sachinart** [detectify/page-fetch#2]
Hi, It's throwing me this error "error starting browser: exec: "google-chrome": executable file not found in $PATH" how to fix it?

### **Update**: 

> Sorry the issue is now resolved I installed Google chrome in machine & everything got fixed.

**Just paste this**
```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
```

Thank you :)

**Comment by tomnomnom** [comment]
Glad you got it fixed! :)
